definitions:
  config.DataResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: boolean
      validate_error: {}
    type: object
  controller.LoginParam:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  todomodel.CreateItem:
    properties:
      title:
        type: string
    type: object
  todomodel.UpdateItem:
    properties:
      status:
        type: string
      title:
        type: string
    type: object
info:
  contact:
    email: info@vn-cubesystem.com
    name: CubeSystem Viet Nam
    url: https://vn-cubesystem.com/
  description: 'Language: Golang. Core: Fiber'
  title: Demo CSV API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.LoginParam'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/config.DataResponse'
      security:
      - ApiKeyAuth: []
      summary: Login
      tags:
      - User
  /v1/items:
    get:
      consumes:
      - application/json
      description: Find all
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/config.DataResponse'
      security:
      - ApiKeyAuth: []
      - ApiTokenAuth: []
      summary: Find all
      tags:
      - Item
    post:
      consumes:
      - application/json
      description: Create a new item
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/todomodel.CreateItem'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/config.DataResponse'
      security:
      - ApiKeyAuth: []
      - ApiTokenAuth: []
      summary: Create a new item
      tags:
      - Item
  /v1/items/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/config.DataResponse'
      security:
      - ApiKeyAuth: []
      - ApiTokenAuth: []
      summary: Delete an item
      tags:
      - Item
    get:
      consumes:
      - application/json
      description: Find an item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/config.DataResponse'
      security:
      - ApiKeyAuth: []
      - ApiTokenAuth: []
      summary: Find an item
      tags:
      - Item
    put:
      consumes:
      - application/json
      description: Update an item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/todomodel.UpdateItem'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/config.DataResponse'
      security:
      - ApiKeyAuth: []
      - ApiTokenAuth: []
      summary: Update an item
      tags:
      - Item
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-csv-key
    type: apiKey
  ApiTokenAuth:
    in: header
    name: x-csv-token
    type: apiKey
swagger: "2.0"
